### ISSUE TITLE
which ffmpeg python package to use?

### ISSUE THREAD

**Issue by NanHeSam** [chinaboard/whisperX-service#2]
Thanks for creating the docker image, but when i download and try to execute i got error 

```
  File "/app/app/webservice.py", line 7, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'
```
i think the package is missing from both requirements.txt and Dockerfile pip install
i tried to add just ffmpeg which for me points to `https://github.com/jiashaokun/ffmpeg`

but then i got error when actually trying to transcribe an audio

```
[2024-08-16 21:25:44 +0000] [8] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/app/app/webservice.py", line 89, in load_audio
    ffmpeg.input("pipe:", threads=0)
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'
```

so i believe it's probably not the right ffmpeg python package you are using. so just wondering which package should be used. 
can you also the pypi package and version in the requirements.txt? 

Thanks!

**Comment by chinaboard** [comment]
For this docker image the ffmpeg should come from [apt](https://github.com/chinaboard/whisperX-service/blob/master/Dockerfile#L5-L12).
So please check your system component.

**Comment by NanHeSam** [comment]
i think the apt only install the ffmpeg cli binary, but it cannot be imported from the python script. I tried both build locally and pull your docker image and directly run it and got the same error. I think i was able to fix it by adding [ffmpeg-python](https://github.com/kkroening/ffmpeg-python) in the requirements.txt i can go back and make a pr
